common/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'common.views.handler404'
handler403 = 'common.views.handler403'
handler500 = 'common.views.handler500'

urlpatterns = [
    
]

dashboard/urls.py
from django.urls import path

from django.views.generic import TemplateView

from . import views


urlpatterns = [
    path('', views.DashboardHomeView.as_view(), name="dashboard_home"),
    path('admin/<slug:username>', views.DashboardAdminView.as_view(), name="dashboard_admin"),
    path('user/<slug:username>', views.DashboardUserView.as_view(), name="dashboard_user"),
]

l4gims/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), # new
    path('accounts/', include('registration.urls')),
    path('', include('scoring.urls')), 
    path('dashboard/', include('dashboard.urls')),
]

dashboard/models.py
from django.db import models

# Create your models here.

scoring/models.py
import random
from collections import OrderedDict
from datetime import date
from dateutil.relativedelta import relativedelta

from django.conf import settings
from django.db import models
from django.contrib.postgres.fields import JSONField
#from django.contrib.postgres.fields import ArrayField
from array_field_select.fields import ArrayField

from common.choices import *


class Questionnaire(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    sector = models.IntegerField(
        verbose_name="Votre structure appartient...",
        choices=SECTOR,
    )
    activity = models.IntegerField(
        verbose_name="Quel est votre secteur d'activité ?",
        choices=ACTIVITY,
    )

    num_employees = models.IntegerField(
        verbose_name="Nombre de salariés au Luxembourg au 1er janvier 2018",
        help_text="(personnes dirigeantes, collaborateurs sous CDD et CDI, travailleurs intérimaires, apprentis, stagiaires, élèves et étudiants inclus)",
    )

    num_employee_female = models.IntegerField(
        verbose_name="Salariés de genre féminin (au total) :",
    )

    num_contract_interim = models.IntegerField(
        verbose_name="Nombre de salariés en intérim : ",
    )
    num_contract_temporary = models.IntegerField(
        verbose_name="Nombre de CDD",
    )
    num_contract_permanent = models.IntegerField(
        verbose_name="Nombre de CDI",
    )

    num_employee_disabled = models.IntegerField(
        verbose_name="Nombre de salariés ayant le statut de salariés handicapés :",
    )
    num_employee_redeployed = models.IntegerField(
        verbose_name="Nombre de salariés ayant bénéficié d'un reclassement interne ou externe",
    )
    num_employee_living_in_lux = models.IntegerField(
        verbose_name="Nombre de  salariés residant au Grand-Duché de Luxembourg",
    )
    num_employee_young = models.IntegerField(
        verbose_name="Nombre de salariés de moins de 26 ans",
    )
    num_employee_old = models.IntegerField(
        verbose_name="Nombre de salariés de plus de 50 ans",
    )

    # section 2
    has_diversity_politics = models.IntegerField(
        verbose_name="Votre structure a-t-elle défini une politique de gestion de la diversité ?",
        choices=YES_NO,
        default=0,
    )
    actions_for_diversity = ArrayField(
        models.IntegerField(
            choices=ACTIONS_FOR_DIVERSITY,
        ),
        verbose_name="Vos actions en faveur de la diversité concernent:",
    )
    
    # section 3
    process = ArrayField(
        models.IntegerField(
            choices=PROCESS,
        ),
        verbose_name="Choisissez dans la liste ci-dessous les processus dont dispose votre entreprise",
    )

    # section 4
    work_conditions = ArrayField(
        models.IntegerField(
            choices=WORK_CONDITIONS,
        ),
        verbose_name="Votre structure a-t-elle mis en place des conditions de travail favorisant le bien-être des collaborateurs ?",
    )


    @property
    def completed(self):
        return True
    
    def compute_score(self):
        d = Score.random_data()
        Score.objects.create(
            user = self.user,
            expiration_date = date.today()+relativedelta(year=1),
            values = d,
            current = True,
        )    


class Score(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    expiration_date = models.DateField(null=True)
    expected_after_action = models.ForeignKey("scoring.Action", null=True, on_delete=models.CASCADE)
    values = JSONField()
    current = models.BooleanField(default=False)

    @classmethod
    def random_data(self, seed=123, rep=1):
        #random.seed(seed)
        score_data = dict( (d, random.random()) for k, d in DIVERSITY_TYPE)
        return OrderedDict(( sorted(score_data.items())))
    
    @property
    def global_score(self):
        if not self.values:
            return 0
        s = 0
        for k, v in self.values:
            s += v
        return s / len(self.values)

    def get_score_dict(self):
        s = self.values
        return s

    def get_sorted_score_values(self):
        return OrderedDict(sorted(self.values.items()))

    def get_data_for_radar(self):
        data = self.get_sorted_score_values()
        return [
            {"axis": k, "value": v} for k, v in data.items()
            ]

    def badges(self):
        pass


class Action(models.Model):

    PROCESSUS = (
        (1, "Gestion des effectifs (entrées - sorties)"),
        (2, "Intégration & culture"),
        (3, "Formation"),
        (4, "Evaluation"),
        (5, "Promotion"),
        (6, "Rémunération"),
        (7, "Temps de travail"),
        (8, "Communication"),
        (9, "Participation"),
        (10, "Relations professionnelles"),
    )

    PLANED = 1
    ONGOING = 2
    COMPLETED = 3
    STATUS = (
        (PLANED, "Prévu"),
        (ONGOING, "En cours"),
        (COMPLETED, "Fini"),
    )
    
    # Nom Action / Type diversité / Processus RH / Date / Texte libre / Statut
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=128)
    diversity_type = models.IntegerField(choices=DIVERSITY_TYPE)
    processus = models.IntegerField(choices=PROCESSUS)
    planned_on = models.DateField()
    comment = models.TextField(null=True, blank=True)
    status = models.IntegerField(choices=STATUS)

    def update_score(self):
        score = Score.objects.get(user=self.user, current=True)
        score_data = score.get_score_dict()
        d = self.get_diversity_type_display()
        current_score_diversity = score_data.get(d)
        new_score_diversity = current_score_diversity * 1.1
        score_data[d] = new_score_diversity
        Score.objects.create(
            user = self.user,
            expected_after_action = self,
            expiration_date = self.planned_on + relativedelta(month=3),
            current = False,
            values = score_data,
        )

dashboard/views.py
import random

from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib.auth.models import User, Group
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404

from common.choices import DIVERSITY_TYPE

from scoring.models import Questionnaire, Score, Action
from scoring.utils import get_global_score_for_radar


class DashboardHomeView(RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        user = self.request.user
        username = user.username
        if "AdminIMS" in user.groups.values_list('name', flat=True):
            return '/dashboard/admin/{username}'.format(username=username)
        return "/dashboard/user/{username}".format(username=username)
    

class DashboardAdminView(UserPassesTestMixin, TemplateView):
    template_name = "dashboard_admin.html"

    def test_func(self):
        username = self.kwargs.get("username")
        return (self.request.user.username == username
                    or "IMS" in self.request.user.groups.values_list('name', flat=True))

    def get_context_data(self, *args, **kwargs):
        users = User.objects.filter(
            groups__name="Customer"
        )

        score_data = get_global_score_for_radar()
        return {
            "users": users,
            "score_data": [score_data, score_data, ],
        }


class DashboardUserView(UserPassesTestMixin, TemplateView):
    template_name = "dashboard_user.html"

    def test_func(self):
        username = self.kwargs.get("username")
        return (self.request.user.username == username
                    or "AdminIMS" in self.request.user.groups.values_list('name', flat=True))
    
    def get_context_data(self, *args, **kwargs):
        username = self.kwargs.get("username")
        user = get_object_or_404(User, username=username)

        q = Questionnaire.objects.filter(
            user=user
        ).first()

        try:
            score = Score.objects.get(
                current=True,
                user=user
            )
        except Score.DoesNotExist:
            score = None

        actions = Action.objects.filter(
            user=user,
        )
        past_actions = actions.filter(
            status=Action.COMPLETED,
        )
        ongoing_actions = actions.exclude(
            status=Action.COMPLETED,
        )

        score_data = score.get_data_for_radar() if score else []
        global_score = get_global_score_for_radar()

        return {
            "user": user,
            "q": q,
            "last_score": score,
            "score_data": [score_data, global_score],
            "evol_data": [{"label": "me",
                           "x": [0, 1, 2, 3, 4, 5, 6],
                           "y": [0, 1, 2, 3, 3.5, 3.7, 5],
                           }],
            "score_evolution_data": None,
            "ongoing_actions": ongoing_actions,
            "past_actions": past_actions,
        }

dashboard/templates/dashboard_admin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Mon dashboard admininstrateur{% endblock %}

{% block content %}

{{ user.fist_name }}

<section>
    <h2 class="shadow">Utilisateurs</h2>
    {% if users  %}
    <table id="userTable" class="display">
	<thead>
	    <tr>
		<th>Nom</th>
		<th>Date de création</th>
		<th>Dernière connexion</th>
		<th>Score</th>
		<th>Badges</th>
	    </tr>
	</thead>
	<tbody>
	    {% for user in users %}
	    <tr>
		<td><a href="/dashboard/user/{{ user.username }}">{{ user.username}}</a></td>
		<td> {{ user.date_joined|date:"d/M/Y" }} </td>
		<td> {{ user.last_login|date:"d/M/Y" }} </td>
		<td> {{ user.score.score|default:"N.D" }} </td>
		<td> - </td>
	    </tr>
	    {% endfor %}
	</tbody>
    </table>
    {% else %}
    Pas de données.
    {% endif %}
</section>

<section>
    <h2 class="shadow">Score global Luxembourg</h2>
    
    {% include "scoring/charts/radar.html" %}
</section>

<script type="text/javascript">
 $(document).ready( function () {
     $('#userTable').DataTable({
	 searching: true,
	 ordering:  true
     });
 } );
</script>
{% endblock %}

dashboard/templates/dashboard_user.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Mon dashboard{% endblock %}

{% block content %}

{{ user.first_name }}

{% if not q.completed %}
<div class="go">
    <a class="cta" href="/scoring/measure/">Finir</a>
</div>

{% else %}

<section>
    <h2 class="shadow">Mon score</h2>    
    {% include "scoring/charts/radar.html" %}
    <form action="/scoring/action/new/" method="get" class="center">
	<input type="submit" value="Améliorer mon score" />
    </form>
</section>

<section>
    <h2 class="shadow">Mes badges</h2>
    <div class="badges-box center">
	<div class="badge">
	    <h4>Egalité H/F</h4>
	    <img src="{% static 'badges/gender_gold.png' %}" alt="Gender gold">
	</div>
	<div class="badge">
	    <h4>Race</h4>
	    <img src="{% static 'badges/race_silver.png' %}" alt="Race silver">
	</div>	
	<div class="badge">
	    <h4>Age</h4>
	    <img src="{% static 'badges/age_bronze.png' %}" alt="Age bronze">
	</div>
    </div>    
    <form action="/scoring/action/new/" method="get" class="center">
	<input type="submit" value="Améliorer mon score" />
    </form>
</section>

<section>
    <h2 class="shadow">Evolution de mon score au cours du temps</h2>
    {% include "scoring/charts/line.html" %}
</section>

<section>
    <h2 class="shadow">Mes actions en cours</h2>
    {% if ongoing_actions  %}
    <table id="actionTable" class="display">
	<thead>
	    <tr>
		<th>Nom</th>
		<th>Date de création</th>
		<th>Date de fin prévue</th>
		<th>Processus</th>
		<th>Type de diversité</th>
		<th>Status</th>
	    </tr>
	</thead>
	<tbody>
	    {% for a in ongoing_actions %}
	    <tr>
		<td><a href="/scoring/action/{{ a.pk }}">{{ a.name }}</a></td>
		<td> {{ a.created_on|date:"d/M/Y" }} </td>
		<td> {{ a.planned_on|date:"d/M/Y" }} </td>
		<td> {{ a.get_processus_display }} </td>
		<td> {{ a.get_diversity_type_display }} </td>
		<td> {{ a.get_status_display }} </td>
	    </tr>
	    {% endfor %}
	</tbody>
    </table>
    {% else %}
    Pas de données.
    {% endif %}
    <form action="/scoring/action/similarity/" method="get" class="center">
	<input type="submit" value="Suggestion d'action" />
    </form>    
</section>

<section>
    <h2 class="shadow">Mes actions passées</h2>
    Pas de données.
</section>

{% endif %}


<script type="text/javascript">
 $(document).ready( function () {
     $('#actionTable').DataTable({
	 searching: true,
	 ordering:  true
     });
 } );
</script>

{% endblock %}